// Generated by CoffeeScript 1.11.1
(function() {
  $(window).load(function() {
    var hideQrImage, hideSnsButton, router, setQrImage, setSnsButton, showQrImage, showSnsButton;
    $('#loadImage').hide();
    $('#snsButtons').hide();
    $('#qrImage').hide();
    router = new Backbone.Router;
    router.route("indi/:id/", (function(_this) {
      return function(_id) {
        var query;
        _this.hideSnsButton;
        $("#Popup #loadImage").attr('src', '');
        query = 'id=' + _id;
        return $.ajax('collage.php', {
          type: "GET",
          data: query,
          dataType: "json",
          error: function(jqXHR, textStatus, errorThrown) {},
          success: function(data) {
            _this.showSnsButton;
            setSnsButton(_id);
            setQrImage(_id);
            if (data.isOk) {
              return $('#loadImage').attr('src', "collage/result/" + _id.slice(1) + ".png?" + Math.floor(Math.random() * 10000)).load(function() {
                $('#loadImage').show();
                showSnsButton();
                return $('#postId').text(_id);
              }).error(function() {});
            }
          }
        });
      };
    })(this));
    Backbone.history.start();
    $('#searchSubmitButton').bind('click', (function(_this) {
      return function() {
        var query;
        router.navigate("", {
          trigger: true
        });
        hideSnsButton;
        hideQrImage;
        $("#Popup #loadImage").attr('src', '');
        query = 'id=' + $('#SearchPanelInnerContents #id').val();
        return $.ajax('collage.php', {
          type: "GET",
          data: query,
          dataType: "json",
          error: function(jqXHR, textStatus, errorThrown) {},
          success: function(data) {
            setQrImage($('#SearchPanelInnerContents #id').val());
            setSnsButton($('#SearchPanelInnerContents #id').val().slice(1));
            if (data.isOk) {
              return $('#loadImage').attr('src', "collage/result/" + $('#SearchPanelInnerContents #id').val().slice(1) + ".png?" + Math.floor(Math.random() * 10000)).load(function() {
                $('#loadImage').show();
                showSnsButton();
                return $('#postId').text(_id);
              }).error(function() {});
            }
          }
        });
      };
    })(this));
    hideSnsButton = (function(_this) {
      return function() {
        return $('#snsButtons').hide();
      };
    })(this);
    showSnsButton = (function(_this) {
      return function() {
        return $('#snsButtons').show();
      };
    })(this);
    setSnsButton = (function(_this) {
      return function(_id) {
        var fbURL, lineURL, twitterURL;
        lineURL = "http://line.me/R/msg/text/?" + encodeURIComponent("http://livepit2.pitcom.jp/post.php#indi/" + _id + "/");
        twitterURL = "https://twitter.com/intent/tweet?url=" + encodeURIComponent("http://livepit2.pitcom.jp/post.php#indi/" + _id + "/");
        fbURL = "https://www.facebook.com/sharer.php?u=" + encodeURIComponent("http://livepit2.pitcom.jp/post.php#indi/" + _id + "/");
        $('#snsLineButton').click(function() {
          return window.location.href = lineURL;
        });
        $('#snsTwitterButton').click(function() {
          return window.location.href = twitterURL;
        });
        return $('#snsFacebookButton').click(function() {
          return window.location.href = fbURL;
        });
      };
    })(this);
    hideQrImage = (function(_this) {
      return function() {
        return $('#qrImage').hide();
      };
    })(this);
    showQrImage = (function(_this) {
      return function() {
        return $('#qrImage').show();
      };
    })(this);
    return setQrImage = (function(_this) {
      return function(_id) {
        return $('#qrImage').attr('src', 'lib/qr_img.php?d=' + encodeURIComponent("http://live.pitcom.jp/post.php#indi/" + _id + "/?utm_source=framecollage&utm_medium=qr&utm_campaign=" + _id) + '&e=M&t=P&' + Math.floor(Math.random() * 10000)).load(function() {
          return showQrImage();
        });
      };
    })(this);
  });

}).call(this);
